### ISSUE TITLE
Unable to connect 

### ISSUE THREAD

**Issue by christopher317** [mika314/obs-airplay#6]
I was able to build the plugin just fine, but when I try to connect with my iPad it fails.

I think the easiest first step to debugging this is to do a checksum on the build to make sure I didn’t mess anything up. For that I need a correct checksum to compare, where would I get said checksum?

https://user-images.githubusercontent.com/86526198/219993576-b3006f59-f51d-4823-bed2-821020b2cec5.mp4

**Comment by mika314** [comment]
What is the checksum of the build?

Try first standalone UxPlay https://github.com/FDH2/UxPlay, if it does not work something wrong with UxPlay. If UxPlay works something else wrong in the OBS plug-in.

**Comment by christopher317** [comment]
MD5: d3861bb93f95779702dfc2b65f42a4f9

il let you know what happens once i grab a build of UxPlay.

PS: i forgot to mention this in the first message of the issue but for some reason libobs didn't want to install, i just assumed that because i already had obs installed that it wouldn't be a problem but now that i think about it, it probably was.

**Comment by christopher317** [comment]
Its UxPlay, nothing new showed up in the console when i tried to connect. ( tho it did look like it booted up correctly )
![image](https://user-images.githubusercontent.com/86526198/220206255-de0c0df3-9bb8-40eb-a506-db23a2e2dad2.png)
( also, not sure if it matters but im on Linux mint, why do i keep forgetting to mention important things )

**Comment by mika314** [comment]
So something is not right with UxPlay.

I still have no idea what kind of checksum of the build you are talking about.

**Comment by christopher317** [comment]
> So something is not right with UxPlay.
> 
> I still have no idea what kind of checksum of the build you are talking about.

yeh honestly idk why i was thinking a checksum would help.

but in the end, yes it is UxPlay, i made sure im not just being a moron and checked the firewall, nothing looks wrong. 
i enabled debug level logging in UxPlay and still nothing showed up. whatever's going on i have no idea.

im going to shift focus from debugging the plugin to debugging UxPlay. if i fix it il edit this comment with what i did to fix it in case someone else has the issue.
